### ISSUE TITLE
404 on landing :(

### ISSUE THREAD

**Issue by jollyjerr** [gecko25/show-me-the-music#2]
I wanted to see what you are up to but its not working :(
<img width="420" alt="Screen Shot 2021-11-04 at 10 30 11 AM" src="https://user-images.githubusercontent.com/51095001/140380021-8ae86813-4a44-421e-9dff-ef6e0eb1671e.png">

Just messing with ya ☺️ . I miss you and hope you are doing well!!

**Comment by gecko25** [comment]
omg @jollyjerr ! Im so stoked you were poking around here. This was fixed with the other issue I was working on #1! So you should see something now. It's not much. Im driving towards something like this --> https://www.showmethemusic.co/ (note the date here doesn't work).
